language: node_js
services:
  - xvfb
node_js:
  - "8"
script:
  - npm run check
after_success:
  - "cat coverage/lcov.info | coveralls --verbose"
cache:
  directories:
  - $HOME/.npm
  - node_modules
addons:
  firefox: "latest"
